version: "3.8"

services:
  frontend:
    image: dockersamples/examplevotingapp_vote
    ports:
      - "8080:80"
    networks: [app-net]
    deploy:
      replicas: 2

  api:
    image: dockersamples/examplevotingapp_worker
    networks: [app-net]
    deploy:
      replicas: 2

  db:
    image: redis:alpine
    networks: [app-net]
    deploy:
      replicas: 1

networks:
  app-net:
    driver: overlay
